example-module-enable: true
dependencies: {  }
fallback_approval_code: 01US20EUC0121
content_types_supported:
  blog_post: 1
  landing_page: 1
  events: 0
  news: 0
  page: 1
_core:
  default_config_hash: OdZt4zPgXzd25QMDtGJI2imd_Ug9kE-Qng8TUImLXVE
