buttons_size: 32
additional_html: "<a class=\"a2a_button_facebook analytics--p-social-share\" data-analytics-id=\"share-btn-facebook-[node:nid]\" data-analytics-position=\"Body\"></a>\r\n<a class=\"a2a_button_twitter analytics--p-social-share\" data-analytics-id=\"share-btn-twitter-[node:nid]\" data-analytics-position=\"Body\"></a>\r\n<a class=\"a2a_button_email analytics--p-social-share\" data-analytics-id=\"share-btn-email-[node:nid]\" data-analytics-position=\"Body\"></a>"
additional_css: ''
additional_js: ''
universal_button: default
custom_universal_button: ''
universal_button_placement: before
no_3p: false
entities:
  media: 1
  node: 1
  comment: 1
  block_content: 0
  contact_message: 0
  crop: 0
  file: 0
  menu_link_content: 0
  paragraphs_library_item: 0
  path_alias: 0
  redirect: 0
  shortcut: 0
  taxonomy_term: 0
  user: 0
  webform_submission: 0
  paragraph: 0
_core:
  default_config_hash: '-oeXHVXl-m1HE6XR_-FXfNgJOgPuHcOCWSkymfOR7Sc'
