module:
  acquia_purge: 0
  acsf: 0
  acsf_duplication: 0
  acsf_sso: 0
  acsf_theme: 0
  acsf_variables: 0
  addtoany: 0
  admin_toolbar: 0
  admin_toolbar_links_access_filter: 0
  admin_toolbar_search: 0
  admin_toolbar_tools: 0
  adminimal_admin_toolbar: 0
  adobe_launch: 0
  anchor_link: 0
  automated_cron: 0
  better_exposed_filters: 0
  big_pipe: 0
  blazy: 0
  block: 0
  block_content: 0
  block_styles: 0
  bootstrap_external_link_popup: 0
  breakpoint: 0
  captcha: 0
  ckeditor: 0
  color: 0
  comment: 0
  config: 0
  config_filter: 0
  config_split: 0
  config_update: 0
  contact: 0
  contextual: 0
  crop: 0
  csv_serialization: 0
  ctools: 0
  custom_paragraph_behaviors: 0
  datetime: 0
  dblog: 0
  draggableviews: 0
  dynamic_page_cache: 0
  editor: 0
  entity_reference_revisions: 0
  entity_usage: 0
  external_link_popup: 0
  features: 0
  features_ui: 0
  field: 0
  field_group: 0
  field_ui: 0
  file: 0
  filter: 0
  focal_point: 0
  google_tag: 0
  help: 0
  history: 0
  honeypot: 0
  html_template_snippet_manager: 0
  ics_on_demand: 0
  image: 0
  inline_entity_form: 0
  inline_form_errors: 0
  isi: 0
  jquery_ui: 0
  jquery_ui_datepicker: 0
  jquery_ui_slider: 0
  jquery_ui_touch_punch: 0
  libraries: 0
  link: 0
  link_attributes: 0
  login_emailusername: 0
  mailsystem: 0
  media: 0
  media_library: 0
  memcache: 0
  memcache_admin: 0
  menu_breadcrumb: 0
  menu_export: 0
  menu_link_attributes: 0
  menu_link_content: 0
  menu_ui: 0
  metatag: 0
  metatag_verification: 0
  node: 0
  options: 0
  otsuka_condition_switcher: 0
  demo_design_system_module: 0
  otsuka_link_attributes: 0
  otsuka_media: 0
  otsuka_prc_code: 0
  otsuka_sfmc_registration: 0
  otsuka_symptom_questionnaire: 0
  page_cache: 0
  paragraphs_library: 0
  paragraphs_viewmode: 0
  path: 0
  path_alias: 0
  protected_pages: 0
  purge: 0
  purge_drush: 0
  purge_ui: 0
  quick_node_clone: 0
  quickedit: 0
  r4032login: 0
  rdf: 0
  recaptcha: 0
  redirect: 0
  responsive_image: 0
  responsive_tables_filter: 0
  rest: 0
  robotstxt: 0
  samlauth: 0
  search: 0
  serialization: 0
  shield: 0
  shortcut: 0
  simple_sitemap: 0
  simple_sitemap_engines: 0
  static_filepath_router: 0
  styles_api: 0
  svg_image: 0
  svg_image_responsive: 0
  swiftmailer: 0
  system: 0
  tablefield: 0
  tablefield_cellspan: 0
  taxonomy: 0
  text: 0
  token: 0
  toolbar: 0
  tour: 0
  transliterate_filenames: 0
  user: 0
  views_bulk_edit: 0
  views_bulk_operations: 0
  views_data_export: 0
  views_infinite_scroll: 0
  views_ui: 0
  webform: 0
  webform_submission_log: 0
  webform_ui: 0
  extlink: 1
  pathauto: 1
  webform_bootstrap: 1
  externalauth: 10
  views: 10
  paragraphs: 11
  standard: 1000
  eu_cookie_compliance: 1001
theme:
  stable: 0
  classy: 0
  seven: 0
  demo_design_system_theme: 0
profile: standard
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
